apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myallapps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Gagans2104/helm-charts.git
    targetRevision: main
    path: myapps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true